name: tests

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  shortenertests:
    runs-on: ubuntu-latest
    container: golang:1.21

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run unit tests
        run: go test -race -tags=unit fast -coverprofile unit.txt -covermode atomic ./...
      - name: Run integration tests
        run: go test -race -tags=integration fast -coverprofile unit.txt -covermode atomic ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}